apiVersion: v1
kind: ConfigMap
metadata:
  name: launchpad-nginx
data:
  nginx.conf: |-
    daemon off;

    error_log /dev/stdout debug;
    pid /run/nginx.pid; 

    events {
        worker_connections  1024;
    }

    http {

        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout;

        access_log          /dev/stdout main;                                                                                                                                                                                              
        client_body_temp_path /tmp;                                                                                                                                                                                                        
        fastcgi_temp_path /tmp;                                                                                                                                                                                                            
        scgi_temp_path /tmp;                                                                                                                                                                                                               
        proxy_temp_path /tmp;                                                                                                                                                                                                              
        uwsgi_temp_path /tmp;                                                                                                                                                                                                              
        sendfile            on;                                                                                                                                                                                                            
        tcp_nopush          on;                                                                                                                                                                                                            
        tcp_nodelay         on;                                                                                                                                                                                                            
        keepalive_timeout   65;                                                                                                                                                                                                            
        types_hash_max_size 2048;                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
        include             /etc/nginx/mime.types;   
        
        upstream backend {
          server launchpad-backend:8080;
        }      

        upstream frontend {
          server launchpad-frontend:8080;
        }      

        upstream missioncontrol {
          server launchpad-missioncontrol:8080;
        }                 


        server {

            client_body_temp_path /tmp/nginx_client_temp 1 2;

            listen       8080;
            root         /usr/share/nginx/html;

            

            location / {
              add_header 'Access-Control-Allow-Origin' "$http_origin";
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';

              proxy_pass http://frontend/;
            }

            location /status/ {
              add_header 'Access-Control-Allow-Origin' "$http_origin";
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';

              proxy_pass http://missioncontrol/status/;
            }

            location /launchpad/ {
              add_header 'Access-Control-Allow-Origin' "$http_origin";
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';

              proxy_pass http://backend/launchpad/;
            }
        }
    }



