kind: Template
apiVersion: v1
metadata:
  name: launchpad-configmap
  annotations:
    openshift.io/display-name: "Launchpad - Configuration"
    description: This application contains the Launchpad configuration settings
    tags: instant-app,launchpad
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the Launchpad configuration settings
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/openshiftio/launchpad-templates
    template.openshift.io/support-url: https://access.redhat.com
message: "The following service has been created in your project: launchpad-configuration.\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/openshiftio"
labels:
  template: launchpad-configmap
parameters:
- name: LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME
  displayName: Your GitHub username
  description: Your GitHub username (leave empty when using Keycloak)
- name: LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN
  displayName: Your GitHub Mission Control access token
  description: Your GitHub Mission Control access token (leave empty when using Keycloak)
- name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
  displayName: Target OpenShift API URL
  description: The base URL of the OpenShift API where the launched boosters
    should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
    Leave the default value when targetting the same OpenShift/Minishift you are
    running this on
  value: https://openshift.default.svc.cluster.local
- name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
  displayName: Target OpenShift Console URL
  description: The base URL of the OpenShift Console where the launched boosters
    should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
    When targetting the same OpenShift/Minishift instance you are running this on you
    can most likely look at this page's address bar of your browser and copy the URL
    Example value (https://$HOSTNAMEORIP:8443)
  value:
- name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME
  displayName: OpenShift user name
  description: OpenShift user (leave empty when using Keycloak)
  value: developer
- name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD
  displayName: OpenShift password
  description: OpenShift password (leave empty when using Keycloak)  
  value: developer
- name: LAUNCHPAD_KEYCLOAK_URL
  displayName: KeyCloak URL
  description: The URL (with the /auth part) of a Keycloak installation to perform SSO
    authentication (leave empty if you've explicitly specified GItHub/OpenShift
    authentication above)
  value: https://sso.openshift.io/auth
- name: LAUNCHPAD_KEYCLOAK_REALM
  displayName: KeyCloak Realm
  description: The keycloak realm to be used (leave empty if you've explicitly specified
    GitHub/OpenShift authentication above)
  value: rh-developers-launch
- name: LAUNCHPAD_TRACKER_SEGMENT_TOKEN
  displayName: Segment Token
  description: The token to use for Segment tracking. Leaving this empty will disable
    tracking. This must be set to the proper tokens for staging and production!
- name: LAUNCHPAD_BACKEND_CATALOG_GIT_REPOSITORY
  displayName: Catalog Git Repository
  description: The GitHub repository containing the booster catalog
  value: https://github.com/openshiftio/booster-catalog.git
  required: true
- name: LAUNCHPAD_BACKEND_CATALOG_GIT_REF
  displayName: Catalog Git Reference
  description: The Git reference to use for the above repository
  value: master
  required: true
- name: LAUNCHPAD_BACKEND_CATALOG_REINDEX_TOKEN
  displayName: Catalog Reindex Token
  description: A token that must be passed to the catalog reindex service to trigger the catalog
    reindexing.
  value:
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: launchpad
  data:
    launchpad.missioncontrol.github.username: ${LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME}
    launchpad.missioncontrol.github.token: ${LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN}
    launchpad.missioncontrol.openshift.username: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_USERNAME}
    launchpad.missioncontrol.openshift.password: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_PASSWORD}
    launchpad.missioncontrol.openshift.api.url: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL}
    launchpad.missioncontrol.openshift.console.url: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL}
    launchpad.backend.catalog.git.repository: ${LAUNCHPAD_BACKEND_CATALOG_GIT_REPOSITORY}
    launchpad.backend.catalog.git.ref: ${LAUNCHPAD_BACKEND_CATALOG_GIT_REF}
    launchpad.backend.catalog.reindex.token: ${LAUNCHPAD_BACKEND_CATALOG_REINDEX_TOKEN}
    launchpad.keycloak.url: ${LAUNCHPAD_KEYCLOAK_URL}
    launchpad.keycloak.realm: ${LAUNCHPAD_KEYCLOAK_REALM}
    launchpad.tracker.segment.token: ${LAUNCHPAD_TRACKER_SEGMENT_TOKEN}
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: launchpad-missioncontrol
  data:
    openshift-clusters.yaml: |-
      - id: starter-us-east-1
        apiUrl: https://api.starter-us-east-1.openshift.com
        consoleUrl: https://console.starter-us-east-1.openshift.com
      - id: starter-us-west-1
        apiUrl: https://api.starter-us-west-1.openshift.com
        consoleUrl: https://console.starter-us-west-1.openshift.com
      - id: starter-us-west-2
        apiUrl: https://api.starter-us-west-2.openshift.com
        consoleUrl: https://console.starter-us-west-2.openshift.com
      - id: starter-ca-central-1
        apiUrl: https://api.starter-ca-central-1.openshift.com
        consoleUrl: https://console.starter-ca-central-1.openshift.com
      - id: pro-us-east-1
        apiUrl: https://api.pro-us-east-1.openshift.com
        consoleUrl: https://console.pro-us-east-1.openshift.com

